
```{r load-packages, include = FALSE}
library(learnr)
library(gradethis)
library(tidyverse)
library(rdrop2)
library(glue)
library(praise)
```

```{r, echo = FALSE}
question_ui_completed.no_mark <- function(question, value, ...) {
  choice_values <- learnr:::answer_values(question)
  disable_all_tags(
    radioButtons(
      question$ids$answer,
      label = question$question,
      choiceValues = choice_values,
      choiceNames = learnr:::answer_labels(question),
      selected = value
    )
  )
}

question_ui_completed.gender <- function(question, value, ...) {
  choice_values <- learnr:::answer_values(question)
  if (value == "Prefer to self describe") {
    textInput(question$ids$answer, label = question$question, 
              placeholder = "Self describe gender", value = "")
  } else {
    disable_all_tags(
      radioButtons(
        question$ids$answer,
        label = question$question,
        choiceValues = choice_values,
        choiceNames = learnr:::answer_labels(question),
        selected = value
      )
    )
  }
}

question_ui_completed.other <- function(question, value, ...) {
  choice_values <- learnr:::answer_values(question)
  if (value == "Other (please specify)") {
    textInput(question$ids$answer, label = question$question, 
              placeholder = "Other, please specify", value = "")
  } else {
    disable_all_tags(
      radioButtons(
        question$ids$answer,
        label = question$question,
        choiceValues = choice_values,
        choiceNames = learnr:::answer_labels(question),
        selected = value
      )
    )
  }
}

question_ui_initialize.numeric <- function(question, value, ...) {
  choice_names <- learnr:::answer_labels(question)
  choice_values <- learnr:::answer_values(question)
  numericInput(question$id$answer, label = question$question,
               value = NA,
               min = min(as.numeric(choice_values)),
               max = max(as.numeric(choice_values)))
}

question_ui_completed.numeric <- function(question, value, ...) {
  disable_all_tags(
    numericInput(question$id$answer,
                 label = question$question,
                 value = value
    )
  )
}
question_is_correct.always_correct <- function(question, value, ...) {
  return(mark_as(TRUE, message = NULL))
}

question_ui_initialize.dropdown <- function(question, value, ...) {
  choice_names <- learnr:::answer_labels(question)
  choice_values <- learnr:::answer_values(question)
  selectInput(question$id$answer, label = question$question,
              choices = choice_names)
}

question_ui_completed.dropdown <- function(question, value, ...) {
  choice_names <- learnr:::answer_labels(question)
  disable_all_tags(
    selectInput(question$id$answer,
                label = question$question,
                choices = choice_names, 
                selected = value
    )
  )
}

question_ui_completed.dropdown_other <- function(question, value, ...) {
  choice_names <- learnr:::answer_labels(question)
  if (value == "Other (please specify)") {
    textInput(question$ids$answer, label = question$question, 
              placeholder = "Other, please specify", value = "")
  } else {
    disable_all_tags(
      selectInput(question$id$answer,
                  label = question$question,
                  choices = choice_names, 
                  selected = value
      )
    )
  }
}

question_ui_initialize.text_area <- function(question, value, ...) {
  textAreaInput(question$id$answer, label = question$question)
}

question_ui_completed.text_area <- function(question, value, ...) {
  disable_all_tags(
    textAreaInput(question$id$answer,
                  label = question$question)
  )
}

```



<!-- ## Log In -->

<!-- Welcome to the Introduction to R modules! To begin, create a username so that you can return later. If you already have a username, click "I am a returning user" below. -->

<!-- ```{r, echo = FALSE} -->
<!-- usernames <- read_csv("usernames.csv") -->
<!-- conditionalPanel("input.return == 0",  -->
<!--                  textInput("user_new", "User Name"), -->
<!--                  uiOutput("username"), -->
<!--                  actionButton("submit", "Submit"), -->
<!--                  br(), br(), -->
<!--                  actionButton("return", "I am a returning user") -->
<!-- ) -->
<!-- conditionalPanel("input.return != 0", -->
<!--                  textInput("user", "User Name"), -->
<!--                  actionButton("login", "Login")) -->
<!-- ``` -->


<!-- ```{r, context = "server"} -->
<!-- output$user <- renderUI({ -->
<!--   if (input$user_new %in% usernames$username) { -->
<!--     "Username is already taken, please enter a different one." -->
<!--   } else { -->
<!--     "" -->
<!--   } -->
<!-- }) -->
<!-- ``` -->


<!-- ```{r, context = "server"} -->
<!-- user <- reactive({ -->
<!--   if (input$user_new == "") { -->
<!--     glue("{sample(praise_parts$adjective, 1)}{sample(1:10000, 1)}") -->
<!--   } else input$user_new -->
<!-- }) -->

<!-- observe({ -->
<!--   updateTextInput(session, "user_new", placeholder = user()) -->
<!-- }) -->

<!-- ``` -->


<!-- ```{r setup, include=FALSE} -->
<!-- drop_auth(rdstoken = "droptoken.rds") -->

<!-- tutorial_options(exercise.checker = gradethis::grade_learnr) -->

<!-- tutorial_event_recorder <- function(username) { -->

<!--   recorder <- function(tutorial_id, tutorial_version, user_id,  -->
<!--                        event, data) { -->
<!--     if (drop_exists(glue("teaching-r-study/data_{user_id}.rds"))) { -->
<!--       drop_download(path = glue("teaching-r-study/data_{user_id}.rds"),  -->
<!--                     local_path = glue("data_{user_id}.rds"), -->
<!--                     overwrite = TRUE) -->
<!--       t <- readRDS(glue("data_{user_id}.rds")) -->
<!--     } else { -->
<!--       t <- tibble( -->
<!--         session = runif(1) * 1e10, -->
<!--         username = username, -->
<!--         time = .POSIXct(numeric(0)), -->
<!--         tutorial_id = character(), -->
<!--         tutorial_version = character(), -->
<!--         user_id = character(), -->
<!--         event = character(), -->
<!--         data = list()) -->

<!--     } -->
<!--     t <- bind_rows(t, -->
<!--                    tibble( -->
<!--                      time = Sys.time(), -->
<!--                      tutorial_id = tutorial_id, -->
<!--                      tutorial_version = tutorial_version, -->
<!--                      user_id = user_id, -->
<!--                      event = event, -->
<!--                      data = list(data) -->
<!--                    ) -->
<!--     ) -->
<!--     saveRDS(t, file = glue("data_{user_id}.rds")) -->
<!--     drop_upload(file = glue("data_{user_id}.rds"), -->
<!--                 path = glue("teaching-r-study")) -->
<!--   } -->
<!--   recorder -->
<!-- } -->
<!-- ``` -->

<!-- ```{r, echo = FALSE, context = "server"} -->
<!-- observe({ -->
<!--   if (input$user %in% usernames$username) { -->
<!--   options(tutorial.event_recorder = tutorial_event_recorder(user)) -->
<!--   } -->
<!-- }) -->
<!-- ``` -->

