---
title: "Demographic Question Code 2"
author: "Jonathan Trattner"
date: "9/15/2020"
output: 
  html_document:
    fig.width: 7
    fig.asp: 0.718
    df_print: paged
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: true
    theme: journal
    highlight: monochrome
    code_folding: hide
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(tidyr)
library(tibble)
library(shinyWidgets)
library(fs)
library(purrr)
library(pander)
library(rlang)
devtools::install_github("jdtrat/taskdesignr")
library(taskdesignr)

# I created a local directory
outputDir <- "storeDemographics"

# function based on Dean Attali's post about persistent data storage
# https://shiny.rstudio.com/articles/persistent-data-storage.html
saveData <- function(data, userID) {
  
  # Create a unique file name
  fileName <- base::sprintf("%s_%s.csv", userID, base::as.integer(base::Sys.time()))
  
  # Write the file to the local system
  readr::write_csv(data,
                   path = base::file.path(outputDir, fileName))
}

```

```{r, echo=FALSE}

shinyApp(

  ui = fluidPage(
    textInput("userID", "Enter your username."),
    # this is using the taskdesignr package.
    # the teaching_r_questions is a sample data set that
    # is included in that package (raw csv file).
    getUICode(teaching_r_questions),
    actionBttn("submit", "Submit"),
    
  ),

  server = function(input, output, session) {
    
    #access session client data -- url port. I'm not sure if this is unique for each visitor with shinyapps.io. I'm including userID just for reference now.
    user_id <- reactive({paste0(input$userID, session$clientData$url_port)})
    
    formData <- reactive({
      data <- tibble::tribble(~userID, ~question, ~response,
                      input$userID, "age", as.character(input$age),
                      input$userID, "gender", input$gender,
                      input$userID, "education_attained", input$education_attained,
                      input$userID, "first_language", input$first_language,
                      input$userID, "read_language", input$read_language,
                      input$userID, "learned_r", input$learned_r,
                      input$userID, "learned_programming_not_r",input$learned_programming_not_r,
                      input$userID, "completed_data_analysis", input$completed_data_analysis
                      )
      data
    })
    
    observeEvent(input$submit, {saveData(data = formData(), userID = user_id())})
    
    },

  options = list(height = 500)
)


```
